In [105]:
import sys
sys.path.append('/data/bionets/og86asub/alternet-project/alternet/')
import pandas as pd
import alternet.data_preprocessing as preprocessing
from alternet.annotation import map_tf_ids
import alternet.annotation as annotation
import alternet.postprocessing as postprocessing

from alternet.inference import *
import yaml
import time
from typing import Any, Dict
import numpy as np

import seaborn as sns

def write_dict_to_yaml(data: Dict[str, Any], filepath: str):
    """Writes a Python dictionary to a YAML file."""

    with open(filepath, 'w') as f:
        yaml.dump(data, f, default_flow_style=False)

In [107]:
config_file = "/data/bionets/og86asub/alternet-project/alternet/configs/MAGNet_NF.yaml"

with open(config_file, 'r') as f:
    config = yaml.safe_load(f)


biomart_path = '/data/bionets/og86asub/alternet-project/alternet/data/biomart.txt'
tf_list_path = '/data/bionets/og86asub/alternet-project/alternet/data/allTFs_hg38.txt'
appris_df = pd.read_csv(config['appris'], sep='\t')

biomart = pd.read_csv(biomart_path, sep='\t')
tf_list = pd.read_csv(tf_list_path, sep='\t', header = None)
tf_list = map_tf_ids(tf_list, biomart)


gene_name_mapper = postprocessing.create_ensg_to_geneid_mapping(biomart)
transcript_name_mapper = postprocessing.create_enst_to_tid_mapping(biomart)

transcript_data = pd.read_csv(config['transcript_data'], index_col=0)

# Subset to protein coding isoforms
protein_coding_isoforms = list(appris_df[appris_df['Transcript type'] == 'protein_coding']['Transcript ID'])
transcript_data = transcript_data[transcript_data.transcript_id.isin(protein_coding_isoforms)]



gene_data = transcript_data.groupby('gene_id').sum()
gene_data = gene_data.drop(columns={'transcript_id'})

gene_data.index.name = 'gene_id'
gene_data = gene_data.reset_index()

sample_attributes = pd.read_csv(config['sample_attributes'])
sample_attributes = sample_attributes.loc[:, ['sample_name', 'etiology']]

conditions = ['DCM']

runs = 10
## Subset the samples of interest
for condi in conditions:

    samples = sample_attributes[sample_attributes['etiology'] == config['tissue']]
    samples = samples['sample_name'].tolist()

    gene_data_cp = gene_data.copy(deep=True)
    transcript_data_cp = transcript_data.copy(deep=True)
    ## Get unified gene and transcript table
    gene_data_cp = gene_data_cp.loc[:, ['gene_id'] + samples ]
    transcript_data_cp = transcript_data_cp.loc[:,['gene_id', 'transcript_id'] + samples]


    gene_target_names = list(tf_list['Gene stable ID'].unique())


    gene_data_cp = gene_data_cp.set_index('gene_id')
    gene_data_cp = gene_data_cp.T

    # scale data!!
    gene_data_cp_scaled = standardize_dataframe(gene_data_cp)

    transcript_data_cp = transcript_data_cp.set_index('transcript_id')
    transcript_data_cp = transcript_data_cp.drop('gene_id', axis=1)
    transcript_data_cp = transcript_data_cp.T

    # scale data!!
    transcript_data_cp_scaled = standardize_dataframe(transcript_data_cp)


    #start = time.monotonic()
    #canonical_grn = inference(gene_data=gene_data_cp, tf_list=gene_target_names, target_names = 'all', n_runs=runs)
    #end = time.monotonic()
    #runtime = {'canonical': end-start}
    
    #canonical_grn.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_canonical.tsv", header = True)

    #hybrid_data = create_hybrid_data(transcript_data_cp, gene_data_cp, tf_list)
    #hybrid_tf_names = list(tf_list['Transcript stable ID'].unique())
    #target_names = list(gene_data_cp.columns)

    #start = time.monotonic()
    #as_aware_grn = inference(gene_data=hybrid_data, tf_list=hybrid_tf_names, target_names=target_names, n_runs = runs)
    #runtime['as_aware'] = time.monotonic()-start

    #as_aware_grn.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_as_aware.tsv", header = True) 
    #write_dict_to_yaml(runtime, f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_runtime.yaml")

    # tf_list = pd.read_csv(tf_list_path, sep='\t', header = None)
    # tf_list = map_tf_ids(tf_list, biomart)

    # #filter aggregate
    # as_aware_grn = pd.read_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_as_aware.tsv", index_col=0)
    # canonical_grn = pd.read_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_canonical.tsv", index_col=0)

    # transcript_mapper = annotation.create_transcript_mapping(biomart)
    # as_aware_grn = postprocessing.map_transcript_to_gene(as_aware_grn, transcript_mapper)

    # as_aware_grn = postprocessing.create_edge_key(as_aware_grn)
    # canonical_grn = postprocessing.create_edge_key(canonical_grn, source_column='source', target_column='target')
    # canonical_grn = canonical_grn.rename(columns={'source': 'source_gene'})


    # # Categorize edges into gene-unique, isoform-unique, common
    # common_edges = postprocessing.get_common_edges(canonical_grn, as_aware_grn)
    # gene_unique, isoform_unique = postprocessing.get_diff(canonical_grn, as_aware_grn)

    # filtering_tracker = {'as_aware_base': as_aware_grn.shape[0], 'canonical_base': canonical_grn.shape[0],  'common_base': common_edges.shape[0], 'gene_unique_base': gene_unique.shape[0], 'isoform_unique_base': isoform_unique.shape[0]}

    # gene_unique, abs_threshold_g, f_gene = postprocessing.filter_aggregated(gene_unique, threshold_importance=0.2, threshold_frequency=10)
    # isoform_unique, abs_threshold_i, f_isoform = postprocessing.filter_aggregated(isoform_unique, threshold_importance=0.2, threshold_frequency=10)


    # filtering_tracker['gene_unique_filter_1'] = f_gene
    # filtering_tracker['isoform_unique_filter_1'] = f_isoform


    # isoform_categories = postprocessing.isoform_categorization(transcript_data_cp, gene_data_cp, tf_list)
    # isoform_categories_sub = isoform_categories.loc[:, ['Gene stable ID', 'Transcript stable ID', 'percentage', 'isoform_category']]

    # isoform_unique, iso_plausibility_filter  = postprocessing.plausibility_filtering(isoform_unique, isoform_categories_sub)
    # filtering_tracker['isoform_unique_plausibility_filter'] = iso_plausibility_filter
    
    # tf_database = annotation.create_transcipt_annotation_database(tf_list=tf_list, appris_path= config['appris'], digger_path=config['digger'])

    # isoform_unique = annotation.merge_annotations_to_grn(isoform_unique, tf_database, transcript_column='source_transcript')
    # isoform_unique  = isoform_unique.drop(columns={'Gene stable ID', 'Transcript stable ID', 'Transcript type'})
    # isoform_unique = isoform_unique.rename(columns = {'target': 'target_gene'})
    # isoform_unique = isoform_unique.add_gene_names(isoform_unique, biomart)
    # isoform_unique.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_unique_isofoms.tsv")

    # gene_categories = postprocessing.get_gene_cases(isoform_categories_sub)
    # gene_unique, filtering_info_gene_plaus = postprocessing.plausibility_filtering_gene_unique(gene_unique, gene_categories)
    # filtering_tracker['gene_unique_plausibility_filter'] = filtering_info_gene_plaus
    # gene_unique = gene_unique.rename(columns = {'target': 'target_gene'})
    # gene_unique = postprocessing.add_gene_names(gene_unique, biomart)
    # gene_unique.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_unique_genes.tsv")


    # merged_edges = postprocessing.create_common_edge_dataframe(common_edges)
    # consistent, ambigous = postprocessing.split_by_isoform_category(merged_edges, gene_categories)
    

    # consistent, filter_info = postprocessing.plausibility_filtering_common_edges_dominant(consistent)
    # filtering_tracker['common_dominant_filter'] = filter_info
    # consistent = postprocessing.add_gene_names(consistent, biomart)
    # consistent.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_consistent_both.tsv")


    # likely_isoform_specific, ambigous, filter_info_iu = postprocessing.find_likely_isoform_specific(ambigous)
    # filtering_tracker['common_isoform_likely_filter'] = filter_info_iu
    # likely_isoform_specific = annotation.merge_annotations_to_grn(likely_isoform_specific, tf_database, transcript_column='source_transcript')
    
    # likely_isoform_specific = postprocessing.add_gene_names(likely_isoform_specific, biomart)
    # likely_isoform_specific.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_likely_isoform_specific.tsv")

    
    # likely_gene_specific, ambigous, filter_infor_gu = postprocessing.find_likely_gene_specific(ambigous)
    # filtering_tracker['common_gene_likely_filter'] = filter_infor_gu
    
    # likely_gene_specific = postprocessing.add_gene_names(edgelist = likely_gene_specific, biomart=biomart)
    # likely_gene_specific.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_likely_gene_specific.tsv")

    # ambigous = postprocessing.add_gene_names(edgelist=ambigous, biomart=biomart)
    # ambigous.to_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_ambigous.tsv")

    # gene_to_transcript_mapping = annotation.create_filtered_gene_to_transcripts_mapping(biomart, gene_list = gene_data_cp_scaled.columns, transcript_list = transcript_data_cp_scaled.columns)
    # correlation_collector = annotation.compute_isoform_gene_correlations(transcript_data_cp_scaled, gene_data_cp_scaled, gene_to_transcript_mapping)

        
    # write_dict_to_yaml(filtering_tracker, f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_filtering_tracker.yaml")

In [1]:
import sys
sys.path.append('/data/bionets/og86asub/alternet-project/alternet/')
import pandas as pd
import alternet.data_preprocessing as preprocessing
from alternet.annotation import map_tf_ids
import alternet.annotation as annotation
import alternet.postprocessing as postprocessing

from alternet.inference import *
import yaml
import time
from typing import Any, Dict
import numpy as np

import seaborn as sns

def write_dict_to_yaml(data: Dict[str, Any], filepath: str):
    """Writes a Python dictionary to a YAML file."""

    with open(filepath, 'w') as f:
        yaml.dump(data, f, default_flow_style=False)

/data/bionets/og86asub/alternet-project/alternet/.pixi/envs/kernel/lib/python3.11/site-packages/numba/core/decorators.py:248: RuntimeWarning: nopython is set for njit and is ignored
  warnings.warn('nopython is set for njit and is ignored', RuntimeWarning)

In [2]:
config_file = "/data/bionets/og86asub/alternet-project/alternet/configs/MAGNet_NF.yaml"

with open(config_file, 'r') as f:
    config = yaml.safe_load(f)


biomart_path = '/data/bionets/og86asub/alternet-project/alternet/data/biomart.txt'
tf_list_path = '/data/bionets/og86asub/alternet-project/alternet/data/allTFs_hg38.txt'
appris_df = pd.read_csv(config['appris'], sep='\t')

biomart = pd.read_csv(biomart_path, sep='\t')
tf_list = pd.read_csv(tf_list_path, sep='\t', header = None)
tf_list = map_tf_ids(tf_list, biomart)

tf_list = pd.read_csv(tf_list_path, sep='\t', header = None)
tf_list = map_tf_ids(tf_list, biomart)
tf_database = annotation.create_transcipt_annotation_database(tf_list=tf_list, appris_path= config['appris'], digger_path=config['digger'])

/data/bionets/og86asub/alternet-project/alternet/src/alternet/annotation.py:91: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  digger = pd.read_csv(digger_path)

In [73]:
appris_df = pd.read_csv(config['appris'], sep='\t')

In [74]:
appris_df

,Ensembl Gene ID,Gene name (HGNC),Transcript ID,Translation ID,Is translated?,Transcript type,Not found tag,CCDS ID,Transcript support level,Protein length,...,Structure score (Matador),Conservation (CORSAIR),Domain Score (SPADE),Trans-membrane helices (THUMP),Signal sequence (CRASH),Trifid Score,Peptides,APPRIS score,APPRIS Annotation,MANE
0,ENSG00000186510,CLCNKA,ENST00000491433,-,NO_TRANSLATION,protein_coding_CDS_not_defined,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ENSG00000186510,CLCNKA,ENST00000331433,ENSP00000332771,TRANSLATION,protein_coding,-,CCDS167.1,1,687.0,...,15.05,7.2,273.6,12.0,"-4,-6",0.9990,-,10.000,ALTERNATIVE:1,MANE_Select
2,ENSG00000186510,CLCNKA,ENST00000439316,ENSP00000414445,TRANSLATION,protein_coding,-,CCDS57973.1,2,644.0,...,14.05,3.2,264.4,12.0,"-4,-5",0.3248,-,6.712,MINOR,NaN
3,ENSG00000186510,CLCNKA,ENST00000464764,-,NO_TRANSLATION,protein_coding_CDS_not_defined,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ENSG00000186510,CLCNKA,ENST00000375692,ENSP00000364844,TRANSLATION,protein_coding,-,CCDS41269.1,1,686.0,...,14.90,7.2,273.6,12.0,"-4,-6",1.0000,-,9.700,PRINCIPAL:4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170707,ENSG00000198695,MT-ND6,ENST00000361681,ENSP00000354665,TRANSLATION,protein_coding,stop,-,-,174.0,...,1.00,4.2,59.1,0.0,"0,-5",0.7910,1,-2.000,PRINCIPAL:1,NaN
170708,ENSG00000228253,MT-ATP8,ENST00000361851,ENSP00000355265,TRANSLATION,protein_coding,-,-,-,68.0,...,0.60,1.0,68.6,0.0,"-2,-5",0.5435,5,12.000,PRINCIPAL:1,NaN
170709,ENSG00000198888,MT-ND1,ENST00000361390,ENSP00000354687,TRANSLATION,protein_coding,start/stop,-,-,318.0,...,1.00,2.5,352.9,0.0,"1,-3",0.7302,5,-2.000,PRINCIPAL:1,NaN
170710,ENSG00000198886,MT-ND4,ENST00000361381,ENSP00000354961,TRANSLATION,protein_coding,stop,-,-,459.0,...,1.00,10.6,265.4,0.0,"0,-4",1.0000,7,-2.000,PRINCIPAL:1,NaN
170711,ENSG00000198938,MT-CO3,ENST00000362079,ENSP00000354982,TRANSLATION,protein_coding,stop,-,-,261.0,...,1.00,29.6,426.0,0.0,"-3,-5",1.0000,2,-2.000,PRINCIPAL:1,NaN

In [ ]:

def get_common_annotation_dataframe(unique_genes, annotation_database):
    '''
    Build a transcript-level annotation table for a set of unique transcription factor (TF) isoforms.

    Parameters:

        unique_tfs : list
            List of Ensembl transcript IDs corresponding to unique TF isoforms.

        annotation_database : pd.DataFrame
            DataFrame containing APPRIS, DIGGER, and Ensembl annotation data.

    Returns:
    
        pd.DataFrame
            DataFrame indexed by transcript ID, containing annotation information for each TF isoform.

    
    '''
    # Precompute annotations for all transcripts
    annotations = []
    for gid in unique_genes.keys():
        annot = get_common_annotations(gid, unique_genes[gid], annotation_database)
        annot['Gene stable ID'] = gid
        annotations.append(annot)
    annotation_df = pd.DataFrame(annotations).set_index('Gene stable ID')
    return annotation_df



def annotate_gene_exclusive_edges(grn, annotation_database, gene_transcript_mapping, gene_column = 'source_gene', transcript_column = 'source_transcript'):
    '''
    Merge transcript-level annotations into a gene regulatory network (GRN) based on source transcript IDs.

    Parameters:

        grn : pd.DataFrame
            DataFrame representing the gene regulatory network, containing a 'source' column with transcript IDs.

        annotation_database : pd.DataFrame
            DataFrame containing APPRIS, and DIGGER annotation data.

    Returns:
    
        pd.DataFrame
            GRN DataFrame with additional columns from the annotation database merged on the 'source' transcript ID.

    '''

    #gene_transcript_mapping = grn.groupby(gene_column)[transcript_column].unique().apply(list).to_dict()
    annot_df = get_common_annotation_dataframe(gene_transcript_mapping, annotation_database)
    grn_annot = grn.merge(annot_df, how='left', left_on=gene_column, right_index=True)
    return grn_annot



def get_intersection(relevant_items):

    relevant_items = [set(tl)  for tl in relevant_items]

    if len(relevant_items)>1:
        common_elements = relevant_items[0].intersection(*relevant_items[1:])
    elif len(relevant_items)>0:
        common_elements = relevant_items[0]
    else:
        common_elements = []
    return list(common_elements)



def get_intersection_wrapper(transcript_data, transcript_info):
    '''
    Compares 'Exon stable ID' and 'Pfam ID' from a transcript dictionary and a DataFrame
    of related isoforms, and returns a dictionary with unique values for each of these columns.

    Parameters:

        transcript_dict : dict
            Dictionary containing 'Exon stable ID' and 'Pfam ID' for a single transcript.

        isoforms_df : pd.DataFrame
            DataFrame containing related isoforms with 'Exon stable ID' and 'Pfam ID' columns.

    Returns:
    
        dict
            A dictionary with keys 'unique_exons' and 'unique_pfam', containing lists of unique values.
    '''


    for col, unique_key in [('Exon stable ID', 'common Exon stable ID'),
                            ('Pfam ID', 'common Pfam ID')]:
        transcript_data[unique_key] = get_intersection(transcript_info.get(col).dropna())

    return transcript_data


def get_common_annotations(gene_id, transcript_ids, annotation_database):

    '''
    Get the available annotations of the transcript and compile a unique list of exon IDs and Pfam IDs.

    Parameters:

        transcript_id : str
            Ensembl ID of the transcript.

        annotation_database : pd.DataFrame
            DataFrame containing APPRIS, and DIGGER annotation data.

    Returns:
    
        dict
            A dictionary containing all annotations of the transcript, including unique exon IDs and Pfam IDs.
  
    '''

    gene = annotation_database[annotation_database['Gene stable ID'] == gene_id]

    if gene.empty:
        # return same structure with None values if transcript not found
        return pd.Series({
            'Protein Coding': False,
            'Transcript type': None,
            'APPRIS Annotation': None,
            'Exon stable ID': None,
            'common Exon stable ID': None,
            'Pfam ID': None,
            'common Pfam ID': None
        })
    

    
    relevant_transcripts = gene[gene['Transcript stable ID'].isin(transcript_ids)]

    if relevant_transcripts.shape[0]==0:
        return pd.Series({
            'Protein Coding': False,
            'Transcript type': None,
            'APPRIS Annotation': None,
            'Exon stable ID': None,
            'common Exon stable ID': None,
            'Pfam ID': None,
            'common Pfam ID': None
        })

    g_row = relevant_transcripts.iloc[0]

    transcript_data = {
        'Protein Coding': True,
        'Transcript type': g_row.get('Transcript type'),
        'APPRIS Annotation': g_row.get('APPRIS Annotation'),
        'Trifid Score': g_row.get('Trifid Score'),
        'Exon stable ID': g_row.get('Exon stable ID'),
        'Pfam ID': g_row.get('Pfam ID'),
    }


    # for compare the transcript data against the chosen set to find out what makes the transcript unique.
    unique_items = get_intersection_wrapper(transcript_data, relevant_transcripts)
    return pd.Series(unique_items)

In [113]:
condi = 'NF'
ambigous = pd.read_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/DCM_unique_genes.tsv")

In [115]:


gene_to_transcript_mapping = annotation.create_filtered_gene_to_transcripts_mapping(biomart, gene_list = gene_data_cp_scaled.columns, transcript_list = transcript_data_cp_scaled.columns)

ambigous = annotate_gene_exclusive_edges(ambigous, annotation_database=tf_database, gene_transcript_mapping=gene_to_transcript_mapping)

In [116]:
ambigous

,Unnamed: 0,source_gene,target_gene,frequency,mean_importance,median_importance,edge_key,target_gene_name,Protein Coding,Transcript type,APPRIS Annotation,Exon stable ID,unique Exon stable ID,Pfam ID,unique Pfam ID,Trifid Score,common Exon stable ID,common Pfam ID
0,13939188,ENSG00000185591,ENSG00000118194,10,5.738032,6.113752,ENSG00000185591_ENSG00000118194,TNNT2,True,protein_coding,PRINCIPAL:4,"[ENSE00002328883, ENSE00003476492, ENSE0000132...",NaN,"[PF00096, PF00096, PF00096]",NaN,1.0000,"[ENSE00001262751, ENSE00001300823, ENSE0000126...",[PF00096]
1,13943390,ENSG00000185591,ENSG00000162623,10,6.612220,5.459664,ENSG00000185591_ENSG00000162623,TYW3,True,protein_coding,PRINCIPAL:4,"[ENSE00002328883, ENSE00003476492, ENSE0000132...",NaN,"[PF00096, PF00096, PF00096]",NaN,1.0000,"[ENSE00001262751, ENSE00001300823, ENSE0000126...",[PF00096]
2,7195009,ENSG00000140262,ENSG00000100292,10,4.606507,4.218943,ENSG00000140262_ENSG00000100292,HMOX1,True,protein_coding,ALTERNATIVE:1,"[ENSE00003568449, ENSE00003606443, ENSE0000365...",NaN,[PF00010],NaN,0.9741,"[ENSE00003523777, ENSE00003489614, ENSE0000363...",[PF00010]
3,1972368,ENSG00000092820,ENSG00000198417,10,3.346036,3.361327,ENSG00000092820_ENSG00000198417,MT1F,True,protein_coding,PRINCIPAL:1,"[ENSE00001212701, ENSE00003532760, ENSE0000353...",NaN,"[PF09379, PF09379, PF00373, PF09379, PF00373, ...",NaN,1.0000,"[ENSE00003527117, ENSE00001028545, ENSE0000102...","[PF09379, PF09380, PF00769, PF00373]"
4,10163778,ENSG00000166716,ENSG00000126243,10,3.298565,2.976567,ENSG00000166716_ENSG00000126243,LRFN3,True,protein_coding,PRINCIPAL:1,"[ENSE00002553930, ENSE00002548999, ENSE0000255...",NaN,"[PF00096, PF00096, PF00096, PF16622]",NaN,1.0000,"[ENSE00003533064, ENSE00003654939, ENSE0000355...","[PF16622, PF00096]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,8113671,ENSG00000148308,ENSG00000152422,10,0.616231,0.581777,ENSG00000148308_ENSG00000152422,XRCC4,True,protein_coding,MINOR,"[ENSE00001372100, ENSE00003789769, ENSE0000164...",NaN,"[PF09734, PF09734, PF09734]",NaN,0.0370,"[ENSE00001372100, ENSE00003789769, ENSE0000351...",[PF09734]
70,17252007,ENSG00000256087,ENSG00000134007,10,1.634007,0.566697,ENSG00000256087_ENSG00000134007,ADAM20,True,protein_coding,PRINCIPAL:1,"[ENSE00001124026, ENSE00002515591, ENSE0000251...",NaN,"[PF01352, PF01352, PF00096, PF00096, PF00096, ...",NaN,1.0000,"[ENSE00002463048, ENSE00001124026, ENSE0000251...","[PF00096, PF01352]"
71,14742325,ENSG00000196109,ENSG00000254709,10,0.771264,0.550638,ENSG00000196109_ENSG00000254709,IGLL5,True,protein_coding,MINOR,"[ENSE00002501651, ENSE00002496192, ENSE0000251...",NaN,"[PF00096, PF00096, PF00096, PF00096, PF00096, ...",NaN,0.4670,[ENSE00002496192],"[PF00096, PF13465]"
72,10718651,ENSG00000168813,ENSG00000119121,10,0.580384,0.548661,ENSG00000168813_ENSG00000119121,TRPM6,True,protein_coding,PRINCIPAL:1,"[ENSE00001355115, ENSE00003695352, ENSE0000132...",NaN,"[PF00096, PF00096]",NaN,1.0000,"[ENSE00001185554, ENSE00003695352, ENSE0000132...",[PF00096]
73,15768070,ENSG00000197905,ENSG00000134240,10,0.634797,0.512334,ENSG00000197905_ENSG00000134240,HMGCS2,True,protein_coding,PRINCIPAL:1,"[ENSE00001369261, ENSE00002224630, ENSE0000222...",NaN,"[PF01285, PF01285, PF01285, PF17725, PF17725, ...",NaN,1.0000,"[ENSE00001276077, ENSE00003601570, ENSE0000127...",[PF17725]

In [101]:
ambigous['common Pfam ID'].value_counts()

common Pfam ID
[PF00096]                      86068
[PF01352]                      80706
[]                             77526
[PF00096, PF01352]             50312
[PF00010]                      20831
                               ...
[PF13606, PF12796]               951
[PF05225]                        894
[PF00452]                        839
[PF00096, PF01352, PF13894]      669
[PF05063]                        647
Name: count, Length: 190, dtype: int64

In [25]:
ambigous.groupby('source_gene')['source_transcript'].unique().apply(list).to_dict()

{'ENSG00000001497': ['ENST00000374807', 'ENST00000374811', 'ENST00000469091'],
 'ENSG00000005889': ['ENST00000379188', 'ENST00000539115'],
 'ENSG00000006468': ['ENST00000405192', 'ENST00000405358', 'ENST00000430479'],
 'ENSG00000006704': ['ENST00000424337', 'ENST00000470715', 'ENST00000476977'],
 'ENSG00000007866': ['ENST00000338863', 'ENST00000639578'],
 'ENSG00000010244': ['ENST00000321233', 'ENST00000394670', 'ENST00000394673'],
 'ENSG00000012048': ['ENST00000352993', 'ENST00000357654', 'ENST00000634433'],
 'ENSG00000013441': ['ENST00000321356', 'ENST00000409769'],
 'ENSG00000018189': ['ENST00000226328', 'ENST00000381006', 'ENST00000417478'],
 'ENSG00000018869': ['ENST00000301310', 'ENST00000589143'],
 'ENSG00000019485': ['ENST00000534751', 'ENST00000622142'],
 'ENSG00000020256': ['ENST00000371518', 'ENST00000371523'],
 'ENSG00000025156': ['ENST00000368455', 'ENST00000452194'],
 'ENSG00000025434': ['ENST00000441012', 'ENST00000467728', 'ENST00000481889'],
 'ENSG00000028839': ['ENST00000237264', 'ENST00000613034'],
 'ENSG00000029363': ['ENST00000527536', 'ENST00000531224'],
 'ENSG00000029993': ['ENST00000325307', 'ENST00000419110'],
 'ENSG00000030419': ['ENST00000451136', 'ENST00000457361'],
 'ENSG00000040341': ['ENST00000355780',
  'ENST00000521210',
  'ENST00000522695',
  'ENST00000523533',
  'ENST00000524104'],
 'ENSG00000058729': ['ENST00000283109',
  'ENST00000508447',
  'ENST00000511012',
  'ENST00000511293'],
 'ENSG00000064490': ['ENST00000407360', 'ENST00000536253'],
 'ENSG00000065029': ['ENST00000339411', 'ENST00000373953', 'ENST00000498555'],
 'ENSG00000065534': ['ENST00000360772', 'ENST00000418370', 'ENST00000515434'],
 'ENSG00000066336': ['ENST00000227163', 'ENST00000378538', 'ENST00000533968'],
 'ENSG00000068305': ['ENST00000354410', 'ENST00000449277', 'ENST00000557942'],
 'ENSG00000071243': ['ENST00000315870', 'ENST00000339121', 'ENST00000445699'],
 'ENSG00000071564': ['ENST00000585731', 'ENST00000593064'],
 'ENSG00000071575': ['ENST00000155926', 'ENST00000381465', 'ENST00000405331'],
 'ENSG00000071626': ['ENST00000233078', 'ENST00000587079', 'ENST00000592522'],
 'ENSG00000071794': ['ENST00000310053', 'ENST00000392912', 'ENST00000465259'],
 'ENSG00000072310': ['ENST00000395757', 'ENST00000478616'],
 'ENSG00000072736': ['ENST00000329524', 'ENST00000346183', 'ENST00000349223'],
 'ENSG00000074219': ['ENST00000311227',
  'ENST00000377214',
  'ENST00000539846',
  'ENST00000593945',
  'ENST00000601519'],
 'ENSG00000074800': ['ENST00000234590', 'ENST00000647408'],
 'ENSG00000075407': ['ENST00000351773', 'ENST00000361085', 'ENST00000638053'],
 'ENSG00000075426': ['ENST00000264716', 'ENST00000379619'],
 'ENSG00000077092': ['ENST00000330688', 'ENST00000458646'],
 'ENSG00000077150': ['ENST00000189444', 'ENST00000369966'],
 'ENSG00000078142': ['ENST00000398870', 'ENST00000589056'],
 'ENSG00000079432': ['ENST00000572681',
  'ENST00000573349',
  'ENST00000575354',
  'ENST00000576505'],
 'ENSG00000080802': ['ENST00000414802',
  'ENST00000423368',
  'ENST00000428680',
  'ENST00000451834'],
 'ENSG00000081189': ['ENST00000340208',
  'ENST00000424173',
  'ENST00000504921',
  'ENST00000636998'],
 'ENSG00000081665': ['ENST00000540806', 'ENST00000545006'],
 'ENSG00000082258': ['ENST00000264157', 'ENST00000295238'],
 'ENSG00000082641': ['ENST00000357480',
  'ENST00000361665',
  'ENST00000362042',
  'ENST00000580037',
  'ENST00000585291'],
 'ENSG00000085063': ['ENST00000351554',
  'ENST00000395850',
  'ENST00000642928',
  'ENST00000651485'],
 'ENSG00000085274': ['ENST00000349841', 'ENST00000356716', 'ENST00000544106'],
 'ENSG00000085276': ['ENST00000264674', 'ENST00000464456', 'ENST00000628990'],
 'ENSG00000085644': ['ENST00000573771', 'ENST00000574902'],
 'ENSG00000087088': ['ENST00000293288', 'ENST00000345358'],
 'ENSG00000088280': ['ENST00000336689', 'ENST00000495646'],
 'ENSG00000088876': ['ENST00000381253', 'ENST00000612935'],
 'ENSG00000089094': ['ENST00000377071', 'ENST00000543852', 'ENST00000611216'],
 'ENSG00000089225': ['ENST00000310346', 'ENST00000349716', 'ENST00000405440'],
 'ENSG00000089335': ['ENST00000423823',
  'ENST00000446502',
  'ENST00000457781',
  'ENST00000505365'],
 'ENSG00000089775': ['ENST00000394715',
  'ENST00000555220',
  'ENST00000555424',
  'ENST00000608382'],
 'ENSG00000090661': ['ENST00000251363', 'ENST00000558877', 'ENST00000559450'],
 'ENSG00000092199': ['ENST00000336053',
  'ENST00000430246',
  'ENST00000554455',
  'ENST00000554969',
  'ENST00000555914',
  'ENST00000556897',
  'ENST00000557768'],
 'ENSG00000092820': ['ENST00000337147', 'ENST00000367075'],
 'ENSG00000095794': ['ENST00000344351',
  'ENST00000356917',
  'ENST00000374726',
  'ENST00000460270',
  'ENST00000469949',
  'ENST00000473940',
  'ENST00000474931',
  'ENST00000488328',
  'ENST00000488741',
  'ENST00000490511'],
 'ENSG00000096654': ['ENST00000211936', 'ENST00000377419'],
 'ENSG00000096746': ['ENST00000265866', 'ENST00000354695'],
 'ENSG00000097007': ['ENST00000318560', 'ENST00000372348', 'ENST00000393293'],
 'ENSG00000099326': ['ENST00000215057', 'ENST00000594108'],
 'ENSG00000100030': ['ENST00000215832', 'ENST00000398822'],
 'ENSG00000100105': ['ENST00000215919', 'ENST00000266269', 'ENST00000351933'],
 'ENSG00000100320': ['ENST00000359369', 'ENST00000405409', 'ENST00000438146'],
 'ENSG00000100644': ['ENST00000323441', 'ENST00000394997', 'ENST00000539097'],
 'ENSG00000100714': ['ENST00000545908', 'ENST00000557370'],
 'ENSG00000100823': ['ENST00000216714', 'ENST00000398030', 'ENST00000555414'],
 'ENSG00000100968': ['ENST00000555393', 'ENST00000555802'],
 'ENSG00000101096': ['ENST00000371564', 'ENST00000396009'],
 'ENSG00000101126': ['ENST00000349014',
  'ENST00000371602',
  'ENST00000396029',
  'ENST00000621696',
  'ENST00000644386'],
 'ENSG00000101190': ['ENST00000217162', 'ENST00000335351'],
 'ENSG00000101811': ['ENST00000372972', 'ENST00000415585'],
 'ENSG00000102038': ['ENST00000371122', 'ENST00000371123'],
 'ENSG00000102103': ['ENST00000247140', 'ENST00000447146'],
 'ENSG00000102317': ['ENST00000354480', 'ENST00000376755', 'ENST00000376759'],
 'ENSG00000102908': ['ENST00000349945', 'ENST00000354436'],
 'ENSG00000103266': ['ENST00000219548', 'ENST00000564316', 'ENST00000566408'],
 'ENSG00000103343': ['ENST00000268655', 'ENST00000572544', 'ENST00000575752'],
 'ENSG00000103495': ['ENST00000563402',
  'ENST00000566906',
  'ENST00000567444',
  'ENST00000568282',
  'ENST00000568544',
  'ENST00000569978'],
 'ENSG00000104529': ['ENST00000317198',
  'ENST00000395119',
  'ENST00000524883',
  'ENST00000525223',
  'ENST00000526340',
  'ENST00000526838',
  'ENST00000528610',
  'ENST00000529272',
  'ENST00000529576',
  'ENST00000530445',
  'ENST00000532543',
  'ENST00000532741',
  'ENST00000534377'],
 'ENSG00000104852': ['ENST00000221448', 'ENST00000598441'],
 'ENSG00000105136': ['ENST00000221735', 'ENST00000347466'],
 'ENSG00000105419': ['ENST00000559524', 'ENST00000560245'],
 'ENSG00000105516': ['ENST00000222122', 'ENST00000593500'],
 'ENSG00000105698': ['ENST00000222305',
  'ENST00000343550',
  'ENST00000594064',
  'ENST00000595068',
  'ENST00000599625'],
 'ENSG00000106261': ['ENST00000324306', 'ENST00000535170'],
 'ENSG00000106459': ['ENST00000393230', 'ENST00000393232'],
 'ENSG00000106628': ['ENST00000223361', 'ENST00000452185', 'ENST00000610533'],
 'ENSG00000107281': ['ENST00000371600', 'ENST00000371601'],
 'ENSG00000108312': ['ENST00000343638', 'ENST00000436088', 'ENST00000533177'],
 'ENSG00000108788': ['ENST00000246912', 'ENST00000346833', 'ENST00000435881'],
 'ENSG00000108953': ['ENST00000264335', 'ENST00000496706', 'ENST00000571732'],
 'ENSG00000109381': ['ENST00000379549', 'ENST00000379550', 'ENST00000394235'],
 'ENSG00000109534': ['ENST00000226796', 'ENST00000394631'],
 'ENSG00000110536': ['ENST00000326656', 'ENST00000326674'],
 'ENSG00000110693': ['ENST00000316399', 'ENST00000396356'],
 'ENSG00000111653': ['ENST00000341550',
  'ENST00000396807',
  'ENST00000412586',
  'ENST00000446105'],
 'ENSG00000112561': ['ENST00000358871',
  'ENST00000394283',
  'ENST00000403298',
  'ENST00000406563'],
 'ENSG00000112651': ['ENST00000230413',
  'ENST00000388752',
  'ENST00000468957',
  'ENST00000487429',
  'ENST00000489623'],
 'ENSG00000112679': ['ENST00000344450', 'ENST00000419235'],
 'ENSG00000113430': ['ENST00000231357', 'ENST00000613726', 'ENST00000622814'],
 'ENSG00000113658': ['ENST00000509297', 'ENST00000545279', 'ENST00000545620'],
 'ENSG00000114126': ['ENST00000479040',
  'ENST00000486111',
  'ENST00000489671',
  'ENST00000499676'],
 'ENSG00000114439': ['ENST00000325805', 'ENST00000415149'],
 'ENSG00000115207': ['ENST00000264720', 'ENST00000423998'],
 'ENSG00000115524': ['ENST00000335508', 'ENST00000424674'],
 'ENSG00000116001': ['ENST00000415783', 'ENST00000433529'],
 'ENSG00000116044': ['ENST00000397062',
  'ENST00000446151',
  'ENST00000458603',
  'ENST00000464747',
  'ENST00000586532',
  'ENST00000588123'],
 'ENSG00000116604': ['ENST00000348159', 'ENST00000464356'],
 'ENSG00000116717': ['ENST00000370986', 'ENST00000617962'],
 'ENSG00000117010': ['ENST00000372696',
  'ENST00000372697',
  'ENST00000372699',
  'ENST00000648542'],
 'ENSG00000117448': ['ENST00000351829',
  'ENST00000372070',
  'ENST00000434299',
  'ENST00000471651',
  'ENST00000621846'],
 'ENSG00000117505': ['ENST00000370267', 'ENST00000370272'],
 'ENSG00000117595': ['ENST00000367021', 'ENST00000456314', 'ENST00000542854'],
 'ENSG00000118260': ['ENST00000353267', 'ENST00000432329', 'ENST00000455757'],
 'ENSG00000119559': ['ENST00000586564', 'ENST00000588427', 'ENST00000588871'],
 'ENSG00000119725': ['ENST00000324593', 'ENST00000334521'],
 'ENSG00000119772': ['ENST00000264709', 'ENST00000406659'],
 'ENSG00000119866': ['ENST00000489516', 'ENST00000642384', 'ENST00000643716'],
 'ENSG00000119950': ['ENST00000332674', 'ENST00000650810', 'ENST00000651004'],
 'ENSG00000120669': ['ENST00000317764', 'ENST00000379881'],
 'ENSG00000120784': ['ENST00000351218', 'ENST00000514101'],
 'ENSG00000120798': ['ENST00000330677', 'ENST00000333003'],
 'ENSG00000120837': ['ENST00000240055', 'ENST00000551446', 'ENST00000551727'],
 'ENSG00000121406': ['ENST00000376233', 'ENST00000602149'],
 'ENSG00000121417': ['ENST00000240731', 'ENST00000391703'],
 'ENSG00000121766': ['ENST00000616393', 'ENST00000618216'],
 'ENSG00000122299': ['ENST00000355758', 'ENST00000396516', 'ENST00000575984'],
 'ENSG00000123415': ['ENST00000243112',
  'ENST00000337581',
  'ENST00000505128',
  'ENST00000508394',
  'ENST00000513838'],
 'ENSG00000124440': ['ENST00000377670', 'ENST00000600383'],
 'ENSG00000124459': ['ENST00000269973', 'ENST00000615985'],
 'ENSG00000124831': ['ENST00000244815', 'ENST00000308482', 'ENST00000420665'],
 'ENSG00000125676': ['ENST00000245838',
  'ENST00000441692',
  'ENST00000448128',
  'ENST00000491737',
  'ENST00000618150'],
 'ENSG00000125733': ['ENST00000313244', 'ENST00000313285', 'ENST00000596758'],
 'ENSG00000125812': ['ENST00000338121', 'ENST00000377051'],
 'ENSG00000125952': ['ENST00000246163', 'ENST00000284165', 'ENST00000358402'],
 'ENSG00000126254': ['ENST00000262633', 'ENST00000588161', 'ENST00000589559'],
 'ENSG00000126351': ['ENST00000264637', 'ENST00000450525', 'ENST00000584985'],
 'ENSG00000126456': ['ENST00000309877', 'ENST00000377139', 'ENST00000601291'],
 'ENSG00000126746': ['ENST00000319770',
  'ENST00000355772',
  'ENST00000396801',
  'ENST00000417772',
  'ENST00000540915'],
 'ENSG00000126804': ['ENST00000358738', 'ENST00000554015'],
 'ENSG00000128000': ['ENST00000221355', 'ENST00000434248'],
 'ENSG00000128928': ['ENST00000479013', 'ENST00000487418', 'ENST00000491554'],
 'ENSG00000129691': ['ENST00000343823', 'ENST00000428278', 'ENST00000545394'],
 'ENSG00000130584': ['ENST00000245663', 'ENST00000395104'],
 'ENSG00000130726': ['ENST00000341753', 'ENST00000594806', 'ENST00000597136'],
 'ENSG00000130803': ['ENST00000247956', 'ENST00000591508'],
 'ENSG00000131127': ['ENST00000240499', 'ENST00000512994'],
 'ENSG00000131368': ['ENST00000253686', 'ENST00000444840', 'ENST00000449354'],
 'ENSG00000131759': ['ENST00000254066', 'ENST00000394081'],
 'ENSG00000131848': ['ENST00000391713', 'ENST00000592355', 'ENST00000592679'],
 'ENSG00000132341': ['ENST00000392367',
  'ENST00000448750',
  'ENST00000535090',
  'ENST00000541679',
  'ENST00000543796'],
 'ENSG00000132604': ['ENST00000254942', 'ENST00000569584'],
 'ENSG00000134453': ['ENST00000379888', 'ENST00000447032'],
 'ENSG00000134758': ['ENST00000257190', 'ENST00000261593'],
 'ENSG00000134954': ['ENST00000392668', 'ENST00000535549'],
 'ENSG00000135111': ['ENST00000257566', 'ENST00000349155'],
 'ENSG00000135486': ['ENST00000330752',
  'ENST00000340913',
  'ENST00000546500',
  'ENST00000547276',
  'ENST00000550482'],
 'ENSG00000135547': ['ENST00000368364', 'ENST00000368365'],
 'ENSG00000135899': ['ENST00000258382', 'ENST00000489597'],
 'ENSG00000136451': ['ENST00000258963', 'ENST00000581208'],
 'ENSG00000136870': ['ENST00000339664', 'ENST00000374861'],
 'ENSG00000136997': ['ENST00000377970', 'ENST00000621592', 'ENST00000652288'],
 'ENSG00000137185': ['ENST00000527436', 'ENST00000531979'],
 'ENSG00000137309': ['ENST00000311487', 'ENST00000347617'],
 'ENSG00000138303': ['ENST00000317126', 'ENST00000317168', 'ENST00000486689'],
 'ENSG00000138380': ['ENST00000402905', 'ENST00000438828'],
 'ENSG00000138738': ['ENST00000264808', 'ENST00000394435'],
 'ENSG00000139154': ['ENST00000266508',
  'ENST00000360995',
  'ENST00000398731',
  'ENST00000512223'],
 'ENSG00000140009': ['ENST00000554572', 'ENST00000556275', 'ENST00000557772'],
 'ENSG00000140262': ['ENST00000267811', 'ENST00000343827', 'ENST00000560948'],
 'ENSG00000140307': ['ENST00000396060',
  'ENST00000396063',
  'ENST00000396064',
  'ENST00000559706'],
 'ENSG00000140382': ['ENST00000336216', 'ENST00000558845'],
 'ENSG00000141040': ['ENST00000395824', 'ENST00000395825'],
 'ENSG00000141510': ['ENST00000504937', 'ENST00000619186'],
 'ENSG00000141644': ['ENST00000353909',
  'ENST00000587605',
  'ENST00000589541',
  'ENST00000591416',
  'ENST00000592060'],
 'ENSG00000141994': ['ENST00000309061', 'ENST00000590343'],
 'ENSG00000142065': ['ENST00000270001', 'ENST00000589280'],
 'ENSG00000143190': ['ENST00000367866', 'ENST00000429375'],
 'ENSG00000143373': ['ENST00000324048', 'ENST00000336715', 'ENST00000443959'],
 'ENSG00000143379': ['ENST00000271640', 'ENST00000368962', 'ENST00000534805'],
 'ENSG00000143995': ['ENST00000272369',
  'ENST00000398506',
  'ENST00000488550',
  'ENST00000495021'],
 'ENSG00000144026': ['ENST00000295208', 'ENST00000447814'],
 'ENSG00000145216': ['ENST00000337488', 'ENST00000358575'],
 'ENSG00000145388': ['ENST00000388822', 'ENST00000506780'],
 'ENSG00000147099': ['ENST00000373554',
  'ENST00000373556',
  'ENST00000373573',
  'ENST00000647859',
  'ENST00000648459',
  'ENST00000650636'],
 'ENSG00000147118': ['ENST00000376943', 'ENST00000396965'],
 'ENSG00000147140': ['ENST00000276079', 'ENST00000373841'],
 'ENSG00000147601': ['ENST00000276602', 'ENST00000276603'],
 'ENSG00000147789': ['ENST00000525266',
  'ENST00000528130',
  'ENST00000528372',
  'ENST00000544249'],
 'ENSG00000147862': ['ENST00000380959', 'ENST00000543693', 'ENST00000606230'],
 'ENSG00000148308': ['ENST00000372099', 'ENST00000372108'],
 'ENSG00000149050': ['ENST00000278314', 'ENST00000536068'],
 'ENSG00000149136': ['ENST00000278412', 'ENST00000635721'],
 'ENSG00000149557': ['ENST00000278919', 'ENST00000366139', 'ENST00000648911'],
 'ENSG00000149929': ['ENST00000279392', 'ENST00000564026'],
 'ENSG00000152217': ['ENST00000426838', 'ENST00000649279'],
 'ENSG00000152284': ['ENST00000282111', 'ENST00000442813'],
 'ENSG00000152443': ['ENST00000317178', 'ENST00000451849'],
 'ENSG00000152804': ['ENST00000282728', 'ENST00000472590'],
 'ENSG00000153814': ['ENST00000283928', 'ENST00000427814'],
 'ENSG00000153896': ['ENST00000329285', 'ENST00000587354', 'ENST00000588760'],
 'ENSG00000154727': ['ENST00000354828', 'ENST00000400075'],
 'ENSG00000154832': ['ENST00000285106', 'ENST00000412036'],
 'ENSG00000154957': ['ENST00000322748', 'ENST00000454073', 'ENST00000580613'],
 'ENSG00000158805': ['ENST00000289816', 'ENST00000443381', 'ENST00000568064'],
 'ENSG00000159692': ['ENST00000382952',
  'ENST00000503594',
  'ENST00000510568',
  'ENST00000513420'],
 'ENSG00000159915': ['ENST00000391958', 'ENST00000589522'],
 'ENSG00000159917': ['ENST00000291182', 'ENST00000650576'],
 'ENSG00000160321': ['ENST00000397126',
  'ENST00000597040',
  'ENST00000599723',
  'ENST00000599916',
  'ENST00000601773'],
 'ENSG00000160336': ['ENST00000610928', 'ENST00000651864'],
 'ENSG00000160352': ['ENST00000456283', 'ENST00000596053'],
 'ENSG00000160741': ['ENST00000368630', 'ENST00000368633'],
 'ENSG00000160908': ['ENST00000337673', 'ENST00000426306'],
 'ENSG00000160917': ['ENST00000292476',
  'ENST00000436336',
  'ENST00000440514',
  'ENST00000451876'],
 'ENSG00000161405': ['ENST00000346872', 'ENST00000623724'],
 'ENSG00000161551': ['ENST00000301399', 'ENST00000639636'],
 'ENSG00000161914': ['ENST00000293771', 'ENST00000592756'],
 'ENSG00000162086': ['ENST00000574298', 'ENST00000612186'],
 'ENSG00000162191': ['ENST00000294119', 'ENST00000301935', 'ENST00000534176'],
 'ENSG00000162367': ['ENST00000294339', 'ENST00000371884'],
 'ENSG00000162664': ['ENST00000340281', 'ENST00000361911'],
 'ENSG00000162702': ['ENST00000294740', 'ENST00000367353'],
 'ENSG00000162714': ['ENST00000294753', 'ENST00000461277'],
 'ENSG00000162772': ['ENST00000341491', 'ENST00000366987'],
 'ENSG00000163110': ['ENST00000317968',
  'ENST00000318007',
  'ENST00000359265',
  'ENST00000380180',
  'ENST00000437932',
  'ENST00000504489',
  'ENST00000508216',
  'ENST00000615540'],
 'ENSG00000163795': ['ENST00000323703', 'ENST00000407879'],
 'ENSG00000164002': ['ENST00000296380', 'ENST00000358527'],
 'ENSG00000164167': ['ENST00000296581', 'ENST00000502781', 'ENST00000649747'],
 'ENSG00000164296': ['ENST00000296736', 'ENST00000515406'],
 'ENSG00000164631': ['ENST00000404360', 'ENST00000405858'],
 'ENSG00000164654': ['ENST00000340080', 'ENST00000405785', 'ENST00000445169'],
 'ENSG00000164920': ['ENST00000297565', 'ENST00000435298'],
 'ENSG00000165156': ['ENST00000395571', 'ENST00000602651'],
 'ENSG00000165804': ['ENST00000360947', 'ENST00000451119'],
 'ENSG00000165821': ['ENST00000537235', 'ENST00000613414'],
 'ENSG00000166261': ['ENST00000336139', 'ENST00000529691'],
 'ENSG00000166526': ['ENST00000299667', 'ENST00000424697'],
 'ENSG00000166704': ['ENST00000341164', 'ENST00000547828'],
 'ENSG00000166716': ['ENST00000299927', 'ENST00000560079'],
 'ENSG00000166925': ['ENST00000300181',
  'ENST00000393991',
  'ENST00000423266',
  'ENST00000456330'],
 'ENSG00000167074': ['ENST00000266304', 'ENST00000406644'],
 'ENSG00000167081': ['ENST00000342287', 'ENST00000447726'],
 'ENSG00000167380': ['ENST00000300823', 'ENST00000337433', 'ENST00000588883'],
 'ENSG00000167395': ['ENST00000300850', 'ENST00000394979'],
 'ENSG00000167528': ['ENST00000301042', 'ENST00000544117'],
 'ENSG00000167555': ['ENST00000360465', 'ENST00000391788', 'ENST00000598192'],
 'ENSG00000167562': ['ENST00000391785', 'ENST00000540331'],
 'ENSG00000167637': ['ENST00000593164', 'ENST00000618787'],
 'ENSG00000167766': ['ENST00000301096', 'ENST00000536937', 'ENST00000597597'],
 'ENSG00000168036': ['ENST00000349496',
  'ENST00000396183',
  'ENST00000396185',
  'ENST00000643031',
  'ENST00000645982'],
 'ENSG00000168066': ['ENST00000227503', 'ENST00000377390', 'ENST00000486867'],
 'ENSG00000168237': ['ENST00000436784', 'ENST00000471180'],
 'ENSG00000168724': ['ENST00000382021', 'ENST00000648817'],
 'ENSG00000168813': ['ENST00000311921', 'ENST00000355898'],
 'ENSG00000169155': ['ENST00000373457', 'ENST00000373464', 'ENST00000449886'],
 'ENSG00000169375': ['ENST00000360439', 'ENST00000394947', 'ENST00000567289'],
 'ENSG00000169554': ['ENST00000629520',
  'ENST00000636413',
  'ENST00000637267',
  'ENST00000638128'],
 'ENSG00000169764': ['ENST00000337130',
  'ENST00000394417',
  'ENST00000445915',
  'ENST00000613823'],
 'ENSG00000169957': ['ENST00000380412', 'ENST00000562803'],
 'ENSG00000170315': ['ENST00000302182',