In [3]:
import pandas as pd
import gprofiler as gp

In [5]:
from gprofiler import GProfiler

gp = GProfiler(return_dataframe=True)
gp.profile(organism='hsapiens',
            query=['NR1H4','TRIP12','UBC','FCRL3','PLXNA3','GDNF','VPS11'])

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents
0,GO:BP,GO:0048486,parasympathetic nervous system development,0.016202,True,"""The process whose specific outcome is the pro...",19,7,2,21026,0.285714,0.105263,query_1,"[GO:0048483, GO:0048731]"
1,GO:BP,GO:0034162,toll-like receptor 9 signaling pathway,0.019891,True,"""The series of molecular signals initiated by ...",21,7,2,21026,0.285714,0.095238,query_1,[GO:0140894]
2,CORUM,CORUM:5669,PlexinA3-Nrp1 complex,0.049932,True,PlexinA3-Nrp1 complex,2,1,1,3383,1.000000,0.500000,query_1,[CORUM:0000000]
3,CORUM,CORUM:5759,PLXNA3-RANBPM complex,0.049932,True,PLXNA3-RANBPM complex,2,1,1,3383,1.000000,0.500000,query_1,[CORUM:0000000]
4,GO:MF,GO:1902122,chenodeoxycholic acid binding,0.049963,True,"""Binding to chenodeoxycholic acid."" [GOC:bf, G...",1,7,1,20246,0.142857,1.000000,query_1,"[GO:0005496, GO:0032052]"

In [6]:
condi = 'NF'
#NF_isoform_unique = pd.read_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_DCM_canonical.tsv")
canonical = pd.read_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_unique_isofoms.tsv")

condi = 'DCM'
DCM_isoform_unique = pd.read_csv(f"/data/bionets/og86asub/alternet-project/alternet-manuscript/results/{condi}_unique_isofoms.tsv")

In [18]:
list(DCM_isoform_unique['target'].unique()[0:200])

['ENSG00000029993',
 'ENSG00000198597',
 'ENSG00000105136',
 'ENSG00000081665',
 'ENSG00000188613',
 'ENSG00000177508',
 'ENSG00000172006',
 'ENSG00000120669',
 'ENSG00000160321',
 'ENSG00000182568',
 'ENSG00000164920',
 'ENSG00000196109',
 'ENSG00000124440',
 'ENSG00000121766',
 'ENSG00000025434',
 'ENSG00000198464',
 'ENSG00000074219',
 'ENSG00000152217',
 'ENSG00000075426',
 'ENSG00000163110',
 'ENSG00000117595',
 'ENSG00000196391',
 'ENSG00000115641',
 'ENSG00000100320',
 'ENSG00000174446',
 'ENSG00000018869',
 'ENSG00000119950',
 'ENSG00000128000',
 'ENSG00000256294',
 'ENSG00000197054',
 'ENSG00000111653',
 'ENSG00000119866',
 'ENSG00000197008',
 'ENSG00000141040',
 'ENSG00000178177',
 'ENSG00000082641',
 'ENSG00000181135',
 'ENSG00000006468',
 'ENSG00000159915',
 'ENSG00000172943',
 'ENSG00000102103',
 'ENSG00000267508',
 'ENSG00000121417',
 'ENSG00000290292',
 'ENSG00000196458',
 'ENSG00000162367',
 'ENSG00000198815',
 'ENSG00000147789',
 'ENSG00000120837',
 'ENSG00000167380',
 'ENSG00000196605',
 'ENSG00000117448',
 'ENSG00000019485',
 'ENSG00000135547',
 'ENSG00000175322',
 'ENSG00000167074',
 'ENSG00000128928',
 'ENSG00000171634',
 'ENSG00000197124',
 'ENSG00000161405',
 'ENSG00000105419',
 'ENSG00000028839',
 'ENSG00000149557',
 'ENSG00000197363',
 'ENSG00000213928',
 'ENSG00000144026',
 'ENSG00000077150',
 'ENSG00000161914',
 'ENSG00000197841',
 'ENSG00000160352',
 'ENSG00000101190',
 'ENSG00000092199',
 'ENSG00000088876',
 'ENSG00000136870',
 'ENSG00000164002',
 'ENSG00000197779',
 'ENSG00000074800',
 'ENSG00000172115',
 'ENSG00000173153',
 'ENSG00000135899',
 'ENSG00000147099',
 'ENSG00000196214',
 'ENSG00000204514',
 'ENSG00000071575',
 'ENSG00000197863',
 'ENSG00000100714',
 'ENSG00000066336',
 'ENSG00000102038',
 'ENSG00000167081',
 'ENSG00000121406',
 'ENSG00000020256',
 'ENSG00000106628',
 'ENSG00000140262',
 'ENSG00000170315',
 'ENSG00000181007',
 'ENSG00000167562',
 'ENSG00000058729',
 'ENSG00000171443',
 'ENSG00000173258',
 'ENSG00000197928',
 'ENSG00000164654',
 'ENSG00000196150',
 'ENSG00000187109',
 'ENSG00000065534',
 'ENSG00000148308',
 'ENSG00000078142',
 'ENSG00000013441',
 'ENSG00000160336',
 'ENSG00000029363',
 'ENSG00000103343',
 'ENSG00000178665',
 'ENSG00000187815',
 'ENSG00000188283',
 'ENSG00000132604',
 'ENSG00000068305',
 'ENSG00000185551',
 'ENSG00000141994',
 'ENSG00000167555',
 'ENSG00000138380',
 'ENSG00000256229',
 'ENSG00000165410',
 'ENSG00000071243',
 'ENSG00000189190',
 'ENSG00000138303',
 'ENSG00000168237',
 'ENSG00000120798',
 'ENSG00000124831',
 'ENSG00000180479',
 'ENSG00000138738',
 'ENSG00000167766',
 'ENSG00000164296',
 'ENSG00000118260',
 'ENSG00000184939',
 'ENSG00000131368',
 'ENSG00000186814',
 'ENSG00000263001',
 'ENSG00000162191',
 'ENSG00000169764',
 'ENSG00000119725',
 'ENSG00000143379',
 'ENSG00000143373',
 'ENSG00000250312',
 'ENSG00000143995',
 'ENSG00000072736',
 'ENSG00000006704',
 'ENSG00000115524',
 'ENSG00000115207',
 'ENSG00000010244',
 'ENSG00000108788',
 'ENSG00000085274',
 'ENSG00000126351',
 'ENSG00000136997',
 'ENSG00000125952',
 'ENSG00000114126',
 'ENSG00000108312',
 'ENSG00000177842',
 'ENSG00000065029',
 'ENSG00000154957',
 'ENSG00000181638',
 'ENSG00000179943',
 'ENSG00000172262',
 'ENSG00000198440',
 'ENSG00000272602',
 'ENSG00000167528',
 'ENSG00000100030',
 'ENSG00000134453',
 'ENSG00000196263',
 'ENSG00000185730',
 'ENSG00000183072',
 'ENSG00000114439',
 'ENSG00000149050',
 'ENSG00000100644',
 'ENSG00000161551',
 'ENSG00000100823',
 'ENSG00000140382',
 'ENSG00000154727',
 'ENSG00000176024',
 'ENSG00000165821',
 'ENSG00000119772',
 'ENSG00000140009',
 'ENSG00000109381',
 'ENSG00000123415',
 'ENSG00000213967',
 'ENSG00000187607',
 'ENSG00000186812',
 'ENSG00000131848',
 'ENSG00000018189',
 'ENSG00000092820',
 'ENSG00000181896',
 'ENSG00000123358',
 'ENSG00000112651',
 'ENSG00000025156',
 'ENSG00000161940',
 'ENSG00000120784',
 'ENSG00000134758',
 'ENSG00000082258',
 'ENSG00000153896',
 'ENSG00000196417',
 'ENSG00000089225',
 'ENSG00000174652']

In [20]:
ghost = gp.profile(organism='hsapiens',
            query=list(DCM_isoform_unique['target'].unique()[0:200]))

In [26]:
ghost[0:20]

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents
0,GO:MF,GO:0003677,DNA binding,1.702227e-105,True,"""Any molecular function by which a gene produc...",2542,200,161,20246,0.805000,0.063336,query_1,[GO:0003676]
1,GO:MF,GO:0003700,DNA-binding transcription factor activity,1.275343e-103,True,"""A transcription regulator activity that modul...",1448,200,135,20246,0.675000,0.093232,query_1,[GO:0140110]
2,GO:MF,GO:0140110,transcription regulator activity,9.237646e-100,True,"""A molecular function that controls the rate, ...",1954,200,145,20246,0.725000,0.074207,query_1,[GO:0003674]
3,GO:MF,GO:0003690,double-stranded DNA binding,5.850834e-99,True,"""Binding to double-stranded DNA."" [GOC:elh, GO...",1644,200,137,20246,0.685000,0.083333,query_1,[GO:0003677]
4,GO:MF,GO:0000977,RNA polymerase II transcription regulatory reg...,7.604689e-99,True,"""Binding to a specific sequence of DNA that is...",1387,200,130,20246,0.650000,0.093727,query_1,[GO:0000976]
5,GO:MF,GO:0000976,transcription cis-regulatory region binding,8.477117e-98,True,"""Binding to a specific sequence of DNA that is...",1485,200,132,20246,0.660000,0.088889,query_1,"[GO:0001067, GO:1990837]"
6,GO:MF,GO:0001067,transcription regulatory region nucleic acid b...,9.270103e-98,True,"""Binding to a nucleic acid region that regulat...",1486,200,132,20246,0.660000,0.088829,query_1,[GO:0003676]
7,GO:MF,GO:1990837,sequence-specific double-stranded DNA binding,7.453047e-97,True,"""Binding to double-stranded DNA of a specific ...",1547,200,133,20246,0.665000,0.085973,query_1,"[GO:0003690, GO:0043565]"
8,GO:MF,GO:0043565,sequence-specific DNA binding,1.148873e-95,True,"""Binding to DNA of a specific nucleotide compo...",1657,200,135,20246,0.675000,0.081473,query_1,[GO:0003677]
9,GO:MF,GO:0000981,"DNA-binding transcription factor activity, RNA...",7.905397e-93,True,"""A DNA-binding transcription factor activity t...",1360,200,125,20246,0.625000,0.091912,query_1,[GO:0003700]
10,GO:BP,GO:0006351,DNA-templated transcription,5.892100e-92,True,"""The synthesis of an RNA transcript from a DNA...",3549,199,166,21026,0.834171,0.046774,query_1,"[GO:0010467, GO:0032774]"
11,GO:BP,GO:0006357,regulation of transcription by RNA polymerase II,1.982833e-91,True,"""Any process that modulates the frequency, rat...",2578,199,150,21026,0.753769,0.058185,query_1,"[GO:0006355, GO:0006366]"
12,GO:BP,GO:0006366,transcription by RNA polymerase II,6.608401e-91,True,"""The synthesis of RNA from a DNA template by R...",2711,199,152,21026,0.763819,0.056068,query_1,[GO:0006351]
13,GO:BP,GO:0051252,regulation of RNA metabolic process,1.190785e-90,True,"""Any process that modulates the frequency, rat...",3687,199,167,21026,0.839196,0.045294,query_1,"[GO:0016070, GO:0019219, GO:0060255]"
14,GO:BP,GO:2001141,regulation of RNA biosynthetic process,3.323964e-90,True,"""Any process that modulates the frequency, rat...",3428,199,163,21026,0.819095,0.047550,query_1,"[GO:0010556, GO:0032774, GO:0051252]"
15,GO:BP,GO:0006355,regulation of DNA-templated transcription,3.262234e-89,True,"""Any process that modulates the frequency, rat...",3409,199,162,21026,0.814070,0.047521,query_1,"[GO:0006351, GO:0010468, GO:2001141]"
16,GO:BP,GO:0019219,regulation of nucleobase-containing compound m...,2.085234e-86,True,"""Any cellular process that modulates the frequ...",3990,199,168,21026,0.844221,0.042105,query_1,"[GO:0006139, GO:0080090]"
17,GO:MF,GO:0000987,cis-regulatory region sequence-specific DNA bi...,3.504168e-81,True,"""Binding to a specific upstream regulatory DNA...",1206,200,112,20246,0.560000,0.092869,query_1,[GO:0000976]
18,GO:MF,GO:0000978,RNA polymerase II cis-regulatory region sequen...,9.027705e-81,True,"""Binding to a specific upstream regulatory DNA...",1183,200,111,20246,0.555000,0.093829,query_1,"[GO:0000977, GO:0000987]"
19,GO:BP,GO:0080090,regulation of primary metabolic process,1.921490e-71,True,"""Any process that modulates the frequency, rat...",5390,199,173,21026,0.869347,0.032096,query_1,"[GO:0019222, GO:0044238]"

In [27]:
for i in range(200):
    print(DCM_isoform_unique['target'].unique()[i])

ENSG00000029993
ENSG00000198597
ENSG00000105136
ENSG00000081665
ENSG00000188613
ENSG00000177508
ENSG00000172006
ENSG00000120669
ENSG00000160321
ENSG00000182568
ENSG00000164920
ENSG00000196109
ENSG00000124440
ENSG00000121766
ENSG00000025434
ENSG00000198464
ENSG00000074219
ENSG00000152217
ENSG00000075426
ENSG00000163110
ENSG00000117595
ENSG00000196391
ENSG00000115641
ENSG00000100320
ENSG00000174446
ENSG00000018869
ENSG00000119950
ENSG00000128000
ENSG00000256294
ENSG00000197054
ENSG00000111653
ENSG00000119866
ENSG00000197008
ENSG00000141040
ENSG00000178177
ENSG00000082641
ENSG00000181135
ENSG00000006468
ENSG00000159915
ENSG00000172943
ENSG00000102103
ENSG00000267508
ENSG00000121417
ENSG00000290292
ENSG00000196458
ENSG00000162367
ENSG00000198815
ENSG00000147789
ENSG00000120837
ENSG00000167380
ENSG00000196605
ENSG00000117448
ENSG00000019485
ENSG00000135547
ENSG00000175322
ENSG00000167074
ENSG00000128928
ENSG00000171634
ENSG00000197124
ENSG00000161405
ENSG00000105419
ENSG00000028839
ENSG00000149557
ENSG00000197363
ENSG00000213928
ENSG00000144026
ENSG00000077150
ENSG00000161914
ENSG00000197841
ENSG00000160352
ENSG00000101190
ENSG00000092199
ENSG00000088876
ENSG00000136870
ENSG00000164002
ENSG00000197779
ENSG00000074800
ENSG00000172115
ENSG00000173153
ENSG00000135899
ENSG00000147099
ENSG00000196214
ENSG00000204514
ENSG00000071575
ENSG00000197863
ENSG00000100714
ENSG00000066336
ENSG00000102038
ENSG00000167081
ENSG00000121406
ENSG00000020256
ENSG00000106628
ENSG00000140262
ENSG00000170315
ENSG00000181007
ENSG00000167562
ENSG00000058729
ENSG00000171443
ENSG00000173258
ENSG00000197928
ENSG00000164654
ENSG00000196150
ENSG00000187109
ENSG00000065534
ENSG00000148308
ENSG00000078142
ENSG00000013441
ENSG00000160336
ENSG00000029363
ENSG00000103343
ENSG00000178665
ENSG00000187815
ENSG00000188283
ENSG00000132604
ENSG00000068305
ENSG00000185551
ENSG00000141994
ENSG00000167555
ENSG00000138380
ENSG00000256229
ENSG00000165410
ENSG00000071243
ENSG00000189190
ENSG00000138303
ENSG00000168237
ENSG00000120798
ENSG00000124831
ENSG00000180479
ENSG00000138738
ENSG00000167766
ENSG00000164296
ENSG00000118260
ENSG00000184939
ENSG00000131368
ENSG00000186814
ENSG00000263001
ENSG00000162191
ENSG00000169764
ENSG00000119725
ENSG00000143379
ENSG00000143373
ENSG00000250312
ENSG00000143995
ENSG00000072736
ENSG00000006704
ENSG00000115524
ENSG00000115207
ENSG00000010244
ENSG00000108788
ENSG00000085274
ENSG00000126351
ENSG00000136997
ENSG00000125952
ENSG00000114126
ENSG00000108312
ENSG00000177842
ENSG00000065029
ENSG00000154957
ENSG00000181638
ENSG00000179943
ENSG00000172262
ENSG00000198440
ENSG00000272602
ENSG00000167528
ENSG00000100030
ENSG00000134453
ENSG00000196263
ENSG00000185730
ENSG00000183072
ENSG00000114439
ENSG00000149050
ENSG00000100644
ENSG00000161551
ENSG00000100823
ENSG00000140382
ENSG00000154727
ENSG00000176024
ENSG00000165821
ENSG00000119772
ENSG00000140009
ENSG00000109381
ENSG00000123415
ENSG00000213967
ENSG00000187607
ENSG00000186812
ENSG00000131848
ENSG00000018189
ENSG00000092820
ENSG00000181896
ENSG00000123358
ENSG00000112651
ENSG00000025156
ENSG00000161940
ENSG00000120784
ENSG00000134758
ENSG00000082258
ENSG00000153896
ENSG00000196417
ENSG00000089225
ENSG00000174652

In [24]:
intersection_of_iso_unique = NF_isoform_unique[NF_isoform_unique.edge_key.isin(set(DCM_isoform_unique.edge_key).intersection(set(NF_isoform_unique.edge_key)))]
intersection_of_iso_unique = intersection_of_iso_unique.reset_index()

In [25]:
top_of_NF = NF_isoform_unique[~NF_isoform_unique.edge_key.isin(set(DCM_isoform_unique.edge_key).intersection(set(NF_isoform_unique.edge_key)))]
top_of_NF = top_of_NF.reset_index()

In [26]:
top_of_DCM = DCM_isoform_unique[~DCM_isoform_unique.edge_key.isin(set(DCM_isoform_unique.edge_key).intersection(set(NF_isoform_unique.edge_key)))]
top_of_DCM = top_of_DCM.reset_index()

In [32]:
for i in range(300):
    print(top_of_DCM.target[i])

ENSG00000185658
ENSG00000082701
ENSG00000258405
ENSG00000116288
ENSG00000111540
ENSG00000143162
ENSG00000139636
ENSG00000127554
ENSG00000197312
ENSG00000132640
ENSG00000130517
ENSG00000147164
ENSG00000133226
ENSG00000197756
ENSG00000109472
ENSG00000168883
ENSG00000136144
ENSG00000080819
ENSG00000180336
ENSG00000148290
ENSG00000125971
ENSG00000113456
ENSG00000233232
ENSG00000113594
ENSG00000163512
ENSG00000101294
ENSG00000180304
ENSG00000162086
ENSG00000169224
ENSG00000131097
ENSG00000106852
ENSG00000164346
ENSG00000132485
ENSG00000143434
ENSG00000135439
ENSG00000125944
ENSG00000174516
ENSG00000088386
ENSG00000196236
ENSG00000085382
ENSG00000160180
ENSG00000137601
ENSG00000138134
ENSG00000165704
ENSG00000165275
ENSG00000004468
ENSG00000101266
ENSG00000079435
ENSG00000198242
ENSG00000119707
ENSG00000144357
ENSG00000181722
ENSG00000172590
ENSG00000160318
ENSG00000124251
ENSG00000130349
ENSG00000180182
ENSG00000121577
ENSG00000272047
ENSG00000150455
ENSG00000147677
ENSG00000170881
ENSG00000134419
ENSG00000138439
ENSG00000181785
ENSG00000085511
ENSG00000111669
ENSG00000175782
ENSG00000129173
ENSG00000119596
ENSG00000163528
ENSG00000107779
ENSG00000154485
ENSG00000099974
ENSG00000143126
ENSG00000136895
ENSG00000162702
ENSG00000152439
ENSG00000111641
ENSG00000187164
ENSG00000171561
ENSG00000158882
ENSG00000142178
ENSG00000188738
ENSG00000081181
ENSG00000104723
ENSG00000150867
ENSG00000160336
ENSG00000099330
ENSG00000196588
ENSG00000174007
ENSG00000074582
ENSG00000047621
ENSG00000178776
ENSG00000155886
ENSG00000162607
ENSG00000142002
ENSG00000164849
ENSG00000116984
ENSG00000188315
ENSG00000130584
ENSG00000162419
ENSG00000189180
ENSG00000172273
ENSG00000057663
ENSG00000129535
ENSG00000177463
ENSG00000009780
ENSG00000169136
ENSG00000167985
ENSG00000178761
ENSG00000081189
ENSG00000158985
ENSG00000022840
ENSG00000181991
ENSG00000127920
ENSG00000110108
ENSG00000112208
ENSG00000187391
ENSG00000107938
ENSG00000166435
ENSG00000126883
ENSG00000198093
ENSG00000166035
ENSG00000117528
ENSG00000074657
ENSG00000116793
ENSG00000145476
ENSG00000181991
ENSG00000197619
ENSG00000214128
ENSG00000006047
ENSG00000164104
ENSG00000173391
ENSG00000124212
ENSG00000196482
ENSG00000141428
ENSG00000170923
ENSG00000092529
ENSG00000165389
ENSG00000137648
ENSG00000214026
ENSG00000170891
ENSG00000163792
ENSG00000197619
ENSG00000138379
ENSG00000145725
ENSG00000021776
ENSG00000176890
ENSG00000203667
ENSG00000130844
ENSG00000096654
ENSG00000147588
ENSG00000227124
ENSG00000178078
ENSG00000120733
ENSG00000203326
ENSG00000126775
ENSG00000185122
ENSG00000198597
ENSG00000088888
ENSG00000169398
ENSG00000118689
ENSG00000163235
ENSG00000155393
ENSG00000102181
ENSG00000101126
ENSG00000248098
ENSG00000120690
ENSG00000161981
ENSG00000158805
ENSG00000121903
ENSG00000214513
ENSG00000257093
ENSG00000119917
ENSG00000178460
ENSG00000110777
ENSG00000205208
ENSG00000268043
ENSG00000276240
ENSG00000179195
ENSG00000103855
ENSG00000105048
ENSG00000102057
ENSG00000126709
ENSG00000101445
ENSG00000174197
ENSG00000214513
ENSG00000069974
ENSG00000126254
ENSG00000134321
ENSG00000163635
ENSG00000114503
ENSG00000126432
ENSG00000137766
ENSG00000123411
ENSG00000143845
ENSG00000233954
ENSG00000102057
ENSG00000177971
ENSG00000101115
ENSG00000197008
ENSG00000197724
ENSG00000123240
ENSG00000105278
ENSG00000137274
ENSG00000132874
ENSG00000143537
ENSG00000185591
ENSG00000076685
ENSG00000182621
ENSG00000081189
ENSG00000101493
ENSG00000157823
ENSG00000085465
ENSG00000143921
ENSG00000137965
ENSG00000164011
ENSG00000120051
ENSG00000168016
ENSG00000157999
ENSG00000164056
ENSG00000063438
ENSG00000187193
ENSG00000006576
ENSG00000158321
ENSG00000100116
ENSG00000103363
ENSG00000115461
ENSG00000134825
ENSG00000266265
ENSG00000112308
ENSG00000109606
ENSG00000127364
ENSG00000176225
ENSG00000116151
ENSG00000126005
ENSG00000152439
ENSG00000204947
ENSG00000002330
ENSG00000266524
ENSG00000038358
ENSG00000106261
ENSG00000130177
ENSG00000185104
ENSG00000164180
ENSG00000175727
ENSG00000118495
ENSG00000151914
ENSG00000101190
ENSG00000141510
ENSG00000153234
ENSG00000124574
ENSG00000088727
ENSG00000088882
ENSG00000163618
ENSG00000184983
ENSG00000168243
ENSG00000140836
ENSG00000183060
ENSG00000100276
ENSG00000156639
ENSG00000214513
ENSG00000168813
ENSG00000124772
ENSG00000172301
ENSG00000174483
ENSG00000166685
ENSG00000163833
ENSG00000091640
ENSG00000164114
ENSG00000145331
ENSG00000014919
ENSG00000204657
ENSG00000235109
ENSG00000100281
ENSG00000162775
ENSG00000132334
ENSG00000176396
ENSG00000122359
ENSG00000159259
ENSG00000103257
ENSG00000182107
ENSG00000188051
ENSG00000147642
ENSG00000129437
ENSG00000116001
ENSG00000095209
ENSG00000154263
ENSG00000083844
ENSG00000196131
ENSG00000174197
ENSG00000106399
ENSG00000104889
ENSG00000130731
ENSG00000137288
ENSG00000161249
ENSG00000152377
ENSG00000119862
ENSG00000214513

In [31]:
for i in range(300):
    print(top_of_NF.target[i])

ENSG00000119866
ENSG00000141040
ENSG00000167074
ENSG00000082641
ENSG00000013441
ENSG00000172943
ENSG00000147789
ENSG00000103343
ENSG00000256294
ENSG00000131368
ENSG00000106628
ENSG00000167562
ENSG00000082641
ENSG00000173153
ENSG00000066336
ENSG00000153896
ENSG00000162086
ENSG00000143995
ENSG00000066336
ENSG00000147140
ENSG00000085063
ENSG00000196417
ENSG00000214029
ENSG00000265241
ENSG00000079432
ENSG00000085063
ENSG00000258289
ENSG00000131368
ENSG00000265241
ENSG00000117505
ENSG00000103343
ENSG00000258289
ENSG00000171291
ENSG00000005700
ENSG00000114270
ENSG00000065978
ENSG00000170949
ENSG00000170949
ENSG00000172869
ENSG00000143995
ENSG00000082641
ENSG00000197951
ENSG00000143995
ENSG00000170949
ENSG00000181785
ENSG00000060339
ENSG00000148450
ENSG00000166441
ENSG00000168653
ENSG00000205268
ENSG00000105339
ENSG00000064102
ENSG00000081386
ENSG00000112276
ENSG00000205629
ENSG00000119866
ENSG00000114270
ENSG00000100294
ENSG00000073849
ENSG00000182070
ENSG00000182400
ENSG00000047315
ENSG00000118197
ENSG00000168137
ENSG00000138434
ENSG00000131779
ENSG00000065665
ENSG00000178982
ENSG00000161010
ENSG00000132541
ENSG00000198964
ENSG00000170881
ENSG00000160180
ENSG00000169762
ENSG00000197714
ENSG00000120254
ENSG00000157429
ENSG00000130714
ENSG00000253873
ENSG00000171649
ENSG00000173418
ENSG00000213995
ENSG00000151150
ENSG00000081386
ENSG00000167685
ENSG00000134882
ENSG00000163322
ENSG00000172053
ENSG00000105135
ENSG00000096070
ENSG00000130449
ENSG00000153317
ENSG00000175334
ENSG00000141198
ENSG00000206562
ENSG00000170276
ENSG00000188613
ENSG00000133835
ENSG00000155097
ENSG00000091831
ENSG00000163558
ENSG00000126883
ENSG00000182070
ENSG00000088280
ENSG00000186479
ENSG00000153896
ENSG00000117523
ENSG00000141642
ENSG00000106459
ENSG00000141627
ENSG00000182108
ENSG00000145388
ENSG00000172869
ENSG00000104327
ENSG00000145996
ENSG00000085063
ENSG00000088826
ENSG00000254901
ENSG00000073849
ENSG00000083223
ENSG00000093072
ENSG00000104112
ENSG00000197763
ENSG00000206262
ENSG00000141580
ENSG00000047644
ENSG00000222014
ENSG00000139714
ENSG00000196172
ENSG00000118094
ENSG00000155287
ENSG00000131849

KeyError: 132

In [30]:
for i in range(200):
    print(intersection_of_iso_unique.target[i])

ENSG00000120669
ENSG00000105136
ENSG00000081665
ENSG00000029993
ENSG00000188613
ENSG00000198597
ENSG00000198597
ENSG00000177508
ENSG00000164920
ENSG00000018869
ENSG00000124440
ENSG00000100320
ENSG00000025434
ENSG00000160321
ENSG00000160321
ENSG00000182568
ENSG00000188613
ENSG00000163110
ENSG00000149557
ENSG00000117595
ENSG00000121766
ENSG00000119950
ENSG00000197008
ENSG00000196391
ENSG00000178177
ENSG00000111653
ENSG00000128000
ENSG00000117595
ENSG00000196109
ENSG00000159915
ENSG00000174446
ENSG00000290292
ENSG00000075426
ENSG00000172006
ENSG00000074219
ENSG00000152217
ENSG00000198464
ENSG00000117448
ENSG00000162367
ENSG00000128928
ENSG00000120837
ENSG00000136870
ENSG00000078142
ENSG00000019485
ENSG00000102103
ENSG00000167380
ENSG00000267508
ENSG00000006468
ENSG00000175322
ENSG00000115641
ENSG00000172115
ENSG00000121417
ENSG00000028839
ENSG00000197124
ENSG00000077150
ENSG00000197863
ENSG00000102038
ENSG00000197779
ENSG00000181007
ENSG00000121406
ENSG00000196458
ENSG00000105419
ENSG00000197363
ENSG00000161914
ENSG00000197054
ENSG00000126351
ENSG00000170315
ENSG00000135547
ENSG00000187109
ENSG00000196605
ENSG00000168237
ENSG00000020256
ENSG00000100714
ENSG00000161405
ENSG00000160321
ENSG00000196214
ENSG00000204514
ENSG00000171634
ENSG00000197841
ENSG00000149557
ENSG00000101190
ENSG00000181135
ENSG00000136997
ENSG00000180479
ENSG00000132604
ENSG00000167081
ENSG00000071243
ENSG00000213928
ENSG00000196150
ENSG00000010244
ENSG00000186814
ENSG00000256229
ENSG00000272602
ENSG00000074800
ENSG00000088876
ENSG00000029363
ENSG00000138303
ENSG00000197054
ENSG00000138380
ENSG00000164002
ENSG00000144026
ENSG00000087088
ENSG00000149050
ENSG00000197363
ENSG00000160336
ENSG00000124831
ENSG00000121766
ENSG00000147099
ENSG00000177842
ENSG00000120798
ENSG00000006704
ENSG00000196263
ENSG00000124440
ENSG00000134758
ENSG00000065534
ENSG00000135899
ENSG00000198815
ENSG00000165410
ENSG00000167766
ENSG00000185730
ENSG00000140262
ENSG00000138738
ENSG00000263001
ENSG00000100644
ENSG00000250312
ENSG00000160352
ENSG00000167555
ENSG00000058729
ENSG00000164654
ENSG00000025156
ENSG00000092199
ENSG00000141994
ENSG00000164920
ENSG00000186812
ENSG00000188283
ENSG00000140009
ENSG00000174953
ENSG00000196391
ENSG00000187815
ENSG00000189190
ENSG00000125952
ENSG00000148308
ENSG00000176024
ENSG00000115207
ENSG00000178665
ENSG00000165821
ENSG00000213967
ENSG00000177508
ENSG00000071575
ENSG00000134453
ENSG00000181638
ENSG00000161940
ENSG00000185551
ENSG00000006468
ENSG00000115524
ENSG00000119725
ENSG00000108788
ENSG00000185630
ENSG00000132341
ENSG00000183072
ENSG00000187607
ENSG00000167528
ENSG00000184939
ENSG00000160321
ENSG00000161551
ENSG00000119559
ENSG00000169764
ENSG00000108312
ENSG00000198440
ENSG00000131848
ENSG00000173258
ENSG00000171163
ENSG00000179943
ENSG00000168610
ENSG00000114126
ENSG00000126351
ENSG00000123358
ENSG00000145216
ENSG00000065029
ENSG00000164296
ENSG00000125968
ENSG00000140382
ENSG00000112651
ENSG00000170315
ENSG00000172262
ENSG00000183309
ENSG00000119772
ENSG00000100823
ENSG00000143190
ENSG00000068305
ENSG00000114126
ENSG00000125733
ENSG00000160352
ENSG00000135111
ENSG00000196268
ENSG00000072736
ENSG00000123415
ENSG00000171443
ENSG00000162664
ENSG00000089225

In [19]:
intersection_of_iso_unique

,index,Unnamed: 0,source_transcript,target,frequency,mean_importance,median_importance,source_gene,edge_key,percentage,isoform_category,Protein Coding,APPRIS Annotation,Trifid Score,Exon stable ID,Pfam ID,unique Exon stable ID,unique Pfam ID
0,0,464608,ENST00000379881,ENSG00000120669,10,139.215951,145.406627,ENSG00000120669,ENSG00000120669_ENSG00000120669,73.237362,non-dominant,True,PRINCIPAL:1,1.0000,"['ENSE00001860914', 'ENSE00003589590', 'ENSE00...","['PF00010', 'PF00010']","['ENSE00003633069', 'ENSE00003595139', 'ENSE00...",['PF00010']
1,1,19147,ENST00000221735,ENSG00000105136,10,138.462532,138.706714,ENSG00000105136,ENSG00000105136_ENSG00000105136,75.464426,non-dominant,True,ALTERNATIVE:2,0.8628,"['ENSE00003655710', 'ENSE00003655710', 'ENSE00...","['PF01352', 'PF01352', 'PF00096', 'PF00096', '...","['ENSE00003481114', 'ENSE00002125865', 'ENSE00...",[]
2,2,808735,ENST00000545006,ENSG00000081665,10,128.893448,124.650110,ENSG00000081665,ENSG00000081665_ENSG00000081665,48.065860,balanced,True,MINOR,0.0046,"['ENSE00001793453', 'ENSE00001600832', 'ENSE00...","['PF01352', 'PF01352']","['ENSE00002283383', 'ENSE00002311175']",[]
3,3,585234,ENST00000419110,ENSG00000029993,10,118.607076,118.287356,ENSG00000029993,ENSG00000029993_ENSG00000029993,64.814718,non-dominant,True,MINOR,0.1479,"['ENSE00001668259', 'ENSE00001287109', 'ENSE00...","['PF09011', 'PF09011', 'PF00505', 'PF00505', '...","['ENSE00001713941', 'ENSE00001668259']",[]
4,4,279709,ENST00000340087,ENSG00000188613,10,110.847293,112.595105,ENSG00000188613,ENSG00000188613_ENSG00000188613,76.666644,non-dominant,True,MINOR,0.1473,['ENSE00001372098'],['PF05741'],['ENSE00001372098'],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10779,793344,990304,ENST00000621805,ENSG00000276231,9,0.229680,0.178477,ENSG00000099246,ENSG00000099246_ENSG00000276231,6.343226,non-dominant,True,MINOR,0.2229,"['ENSE00003612794', 'ENSE00003612794', 'ENSE00...","['PF00071', 'PF00071', 'PF00071', 'PF00071', '...","['ENSE00002229306', 'ENSE00001468427', 'ENSE00...",[]
10780,793604,177417,ENST00000311403,ENSG00000157110,7,0.218017,0.178422,ENSG00000174282,ENSG00000174282_ENSG00000157110,45.268284,balanced,True,PRINCIPAL:1,1.0000,"['ENSE00001202474', 'ENSE00001264161', 'ENSE00...",['PF00651'],"['ENSE00001824494', 'ENSE00001332897']",[]
10781,793642,81446,ENST00000264674,ENSG00000170892,6,0.189908,0.178415,ENSG00000085276,ENSG00000085276_ENSG00000170892,27.879717,non-dominant,True,MINOR,0.1886,"['ENSE00002073683', 'ENSE00002073683', 'ENSE00...","['PF13912', 'PF00096', 'PF00096', 'PF13912', '...","['ENSE00001420306', 'ENSE00003659832', 'ENSE00...",[]
10782,793763,235625,ENST00000330677,ENSG00000164346,8,0.203741,0.178390,ENSG00000120798,ENSG00000120798_ENSG00000164346,22.110735,non-dominant,True,MINOR,0.0119,"['ENSE00003638681', 'ENSE00003523247', 'ENSE00...","['PF00105', 'PF00105', 'PF00104', 'PF00104']","['ENSE00001514185', 'ENSE00002411633']",[]
10783,794580,449285,ENST00000377051,ENSG00000235118,5,0.154034,0.178216,ENSG00000125812,ENSG00000125812_ENSG00000235118,48.304357,balanced,True,PRINCIPAL:1,0.9829,"['ENSE00003471644', 'ENSE00003471644', 'ENSE00...","['PF00096', 'PF13912', 'PF00096', 'PF00096', '...","['ENSE00001421601', 'ENSE00001472624']",[]